name: virtuohero
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  hive_flutter: ^1.1.0
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.5.4

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/mascot.png

  fonts:
  - family: Afacad
    fonts:
      - asset: assets/fonts/Afacad-Regular.ttf
      - asset: assets/fonts/Afacad-Italic.ttf
        style: italic
      - asset: assets/fonts/Afacad-Medium.ttf
        weight: 500
      - asset: assets/fonts/Afacad-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Afacad-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Afacad-SemiBoldItalic.ttf
        weight: 600
        style: italic
      - asset: assets/fonts/Afacad-Bold.ttf
        weight: 700
      - asset: assets/fonts/Afacad-BoldItalic.ttf
        weight: 700
        style: italic
